/// Flutter icons Crud_app
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Crud_app
///      fonts:
///       - asset: fonts/Crud_app.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Crud_app {
  Crud_app._();

  static const _kFontFam = 'Crud_app';

  static const IconData login = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user_add = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData user_plus = const IconData(0xf234, fontFamily: _kFontFam);
}
